CREATE TABLE USER_INFO(
	IDX               INT AUTO_INCREMENT NOT NULL ,
	USER_ID           VARCHAR(20) NOT NULL,
	PASSWORD          VARCHAR(20) NOT NULL,
	NAME_KANJI        VARCHAR(20) NOT NULL,
	NAME_HURIGANA     VARCHAR(20) NOT NULL,
	SEX               VARCHAR(1) NOT NULL,
	BIRTHDATE         DATETIME NOT NULL,
	EMAIL             VARCHAR(200) NOT NULL,
	KAKAO_ID          VARCHAR(20),
	LINE_ID           VARCHAR(20),
	ADDRESS           VARCHAR(200),
	PHONE             VARCHAR(13),
	DEL_FLAG          VARCHAR(1) NOT NULL,
	REG_DATE          DATETIME NOT NULL,
	UPD_DATE          DATETIME NOT NULL,
	DEL_DATE          DATETIME NOT NULL,
	PRIMARY KEY(IDX, USER_ID)
);
